version: '3'

services:
  db:
    image: postgres:13.3-alpine
    container_name: db
    restart: always
    ports:
      - 9090:5432
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=messenger
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./psql_db:/var/lib/postgresql/data/
  redis:
    image: redis:5.0.12-alpine
    container_name: redis
    restart: always
    ports:
      - 9191:6379
  server:
    build: './nest-gateway'
    container_name: server
    restart: always
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - TOKEN=$TOKEN
      - REFRESH_TOKEN=$REFRESH_TOKEN
    ports:
      - 3000:3000
    links:
      - db
      - redis
  ws:
    build: './wsServ'
    container_name: ws
    restart: always
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - TOKEN=$TOKEN
      - REFRESH_TOKEN=$REFRESH_TOKEN
    ports:
      - 5055:5055
    links:
      - db
      - redis
      - server
  message:
    build: './messageServ'
    container_name: message
    restart: always
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
    volumes:
      - .aws/:/root/.aws/
    links:
      - db
      - redis
      - server
  auth:
    build: './authServ'
    container_name: auth
    restart: always
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - TOKEN=$TOKEN
      - REFRESH_TOKEN=$REFRESH_TOKEN
      - EMAIL=$EMAIL
      - PASSWORD_EMAIL=$PASSWORD_EMAIL
    links:
      - db
      - redis
      - server
  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - server
      - ws
    ports:
      - 8080:8080